version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    env_file:
      - docker-compose.env

  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - docker-compose.env
    volumes:
      - cache:/go/pkg

  tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    depends_on:
      - app
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      cd /app 
      CGO_ENABLED=0 go test
    volumes:
      - cache:/go/pkg

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  cache: