apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  POSTGRES_HOST: "{{ .Values.database.host }}"
  POSTGRES_PORT: "{{ .Values.database.port }}"
  POSTGRES_DB: "{{ .Values.database.name }}"
  POSTGRES_USER: "{{ .Values.database.user }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  POSTGRES_PASSWORD: "{{ .Values.database.password | b64enc }}"